version: "3"
services:
      ticketingapp:
              hostname: ticketingapp
              expose:
                 - "3000"
              ports:
                - "3000:3000"
              build:
                 dockerfile: Dockerfile
                 context: .
                 target: build-env