CREATE TABLE user_role (
    user_role_id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    idrole int(6) UNSIGNED,
    iduser int(6) UNSIGNED,
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    modified_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (idrole) REFERENCES role(idrole)
)ENGINE=InnoDB;