CREATE TABLE email_log (
    idemail INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    iduser int(6) UNSIGNED,
    sent bit,
    email_body text,
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    sentAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (iduser) REFERENCES user(iduser)
)
ENGINE=InnoDB;